# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hey There!! 
email: palad@iitk.ac.in
description: >- # this means to ignore newlines until "baseurl:"
  "The fragility of a crystal is not a weakness but a fineness"
baseurl: "home" # the subpath of your site, e.g. /blog
url: "https://paladarsh.pythonanywhere.com" # the base hostname & protocol for your site, e.g. http://example.com
#logo: /images/dp.jpg
twitter_username: AdarshPal2
github_username:  paladarsh
#tagline: "The fragility of a crystal is not its weakness but a fineness "
# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-avatar
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
accent_image: /images/campus.jpg
accent_color: rgb(79,177,186)
#author:
#  name:  Adarsh Pal
#  email: palad@iitk.ac.in
#author:
#  name: Adarsh Pal
#  email: palad@iitk.ac.n
#  about: |
#    This is another paragraph.
#author:
#  picture:  /images/dp.jpg
menu:
#legal
  - title: Home
    url: /
  - title:             About
    url:               /about/
  - title: Resume
    url: ./Resume.pdf
copyright: All rights reserved.
#collections:
#  featured_categories:
#    permalink:         /category/:name/
#    output:            true
#  featured_tags:
#    permalink:         /tag/:name/
#    output:            true